#This code is for workflow level configuration in a CI/CD pipeline in github actions
name: CI/CD Pipeline workflow
on: 
  workflow_dispatch:                      # This workflow can be triggered manually
env:
  User_name: 'DevOpsTeam'
jobs:
  build:
    runs-on: ubuntu-latest                    # This job will run on the latest version of Ubuntu
    steps:                                    # Steps to be executed in the job
      - name: Checkout code                   # Step to checkout the code from the repository
        uses: actions/checkout@v2             # Using the checkout action version 2
      - name: Echo User Name                   # -name is used to give a name to the step
        run: echo "User Name is ${{ env.User_name }}" # run is used to execute a command
