# This workflow runs conditionally based on the event type with if conditionals only run on main branch 
# in this repository have two branches main and test i want this workflow to run only on main branch in if conditionals for prectice

name: Conditional Workflow
on : 
  push:
    branches:
      - "*"       # Trigger on push events to any branch
  pull_request:
    branches:
      - "*"       # Trigger on pull request events to any branch
jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run on push to main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "This job ran on a push event to the main branch."

      - name: Run on pull request to main branch
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: echo "This job ran on a pull request event to the main branch." 
