# Test Ubuntu, Windows, and macOS OS versions using a matrix strategy
name: OS Versions Testing Workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  os-version-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-15.04, ubuntu-20.04, windows-2019, windows-2022, macos-10.15, macos-11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display OS Version
        shell: bash
        run: |
          echo "Running on OS: ${{ matrix.os }}"

          if [[ "${{ matrix.os }}" == ubuntu* ]]; then
            lsb_release -a

          elif [[ "${{ matrix.os }}" == windows* ]]; then
            systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

          elif [[ "${{ matrix.os }}" == macos* ]]; then
            sw_vers
          fi
