#This code is for to get secret variables in a CI/CD pipeline in github actions (AWS_REGION)
name: Secret Variables Configuration
on:
  workflow_dispatch:                      # This workflow can be triggered manually 
jobs:
  deploy:
    runs-on: ubuntu-latest                    # This job will run on the latest version of Ubuntu
    steps:                                    # Steps to be executed in the job
      - name: Checkout code                   # Step to checkout the code from the repository
        uses: actions/checkout@v2             # Using the checkout action version 2
      - name: Echo Secret Variables            # -name is used to give a name to the step
        run: |                               # run is used to execute commands
          echo "Database Password is ${{ secrets.DB_PASSWORD }}"
          echo "API Key is ${{ secrets.API_KEY }}"
